//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 23.02.2016 17:52:56 by NFX.Templatization.TextCSTemplateCompiler at LAPTOP

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using NFX; 
using NFX.Wave; 
using NFX.Wave.Templatization; 
using Tutorial03.Models; 

namespace Tutorial03.Pages 
{

 ///<summary>
 /// Auto-generated from template
 ///</summary>
 public  class Edit : NFX.Wave.Templatization.WaveTemplate 
 {

  public string PersonDef { get; set; }


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Edit._90_S_LITERAL_0 );
        Target.Write( Edit._90_S_LITERAL_1 );
        Target.Write( PersonDef );
        Target.Write( Edit._90_S_LITERAL_2 );

     }


     #region Literal blocks content
        private const string _90_S_LITERAL_0 = @"

"; 
        private const string _90_S_LITERAL_1 = @"
<!DOCTYPE html>

<html>
<head>
  <meta charset=""utf-8"" />
  <title>WAVE Tutorial 02</title>
  <style>
      .wvError {
        color: rgba(255,40,10, 0.7);
        background-color: #fff0e0;
        background: linear-gradient(to right, rgba(255,161,79,0) 0%,rgba(255,161,79,0.15) 2%,rgba(254,171,86,0.23) 3%,rgba(247,229,131,0.22) 9%,rgba(255,180,114,0.2) 18%,rgba(239,239,239,0.08) 69%,rgba(239,239,239,0) 100%);
        padding-left: 8px;
        font-size: 0.9em;
      }

      .wvRequired {
        font-weight: normal;
        text-shadow: 0px 0px 1px rgba(0,0,255, 0.65);
      }

        .wvRequired:before {
          content: ""* "";
        }

      .wvModified {
        border-bottom: 2px dotted #80de40;
      }

      .wvToast {
        display: block;
        position: fixed;
        background: black;
        border: 1px solid #808080;
        width: auto;
        padding: 8px;
        top: 45%;
        left: 50%;
        color: white;
        box-shadow: 2px 2px 10px #888888;
      }

      .wvToast_error {
        display: block;
        position: fixed;
        background: #ff5040;
        border: 1px solid #ff8080;
        width: auto;
        padding: 8px;
        top: 45%;
        left: 50%;
        color: white;
        box-shadow: 2px 2px 10px #888888;
      }

      input[type=number] {
        width: 60px;
      }

      input[type=text], input[type=number] {
        background-color: #f0f0e0;
        border: 1px solid #e0e0e0;
        border-radius: 5px;
        margin: 5px;
      }

        input[type=text]:focus, input[type=number]:focus {
          background-color: #ffffc0;
          border: 1px solid #808080;
          border-radius: 5px;
          margin: 5px;
        }

      input[type=submit] {
        margin-top: 10px;
      }
      .container {
        margin-left: 20%;
        margin-top: 50px;
      }
  </style>
  <script src=""/stock/site/script/jquery-2.1.4.min.js""></script>
  <script src=""/stock/site/script/wv.js""></script>
  <script src=""/stock/site/script/wv.gui.js""></script>
</head>
<body>
  <div class=""container"">
    <form id=""frmPerson"" data-wv-rid=""V1"" action=""edit"" method=""POST"">
      <div data-wv-fname=""ID""></div>
      <div data-wv-fname=""FirstName""></div>
      <div data-wv-fname=""LastName""></div>
      <div data-wv-fname=""Age""></div>
      <div data-wv-fname=""IsCertified""></div>
      <input type=""submit"" value=""Submit"" />
    </form>
  </div>
  <script>
    var REC = new WAVE.RecordModel.Record("; 
        private const string _90_S_LITERAL_2 = @");
    var RVIEW = new WAVE.RecordModel.RecordView(""V1"", REC);

    $('#frmPerson').submit(function (e) {
      if (!REC.validate())
      {
        WAVE.GUI.toast('Please correct all validation errors marked in red','error');
        e.preventDefault();
        return false;
      }
      REC.resetModified();
      return true;
    })
  </script>
</body>
</html>"; 
     #endregion

 }//class
}//namespace
